Test/Test3/Models/AccountModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Api.Requests;
using Models.Auth;

namespace Web.Models
{
    public class AccountModel
    {
        public static void RenewUserInfo()
        {
            var user = GetUser.Get(Authentication.UserId, Authentication.ResponseToken);
            using (Database.Contexts.AudioContext db = new Database.Contexts.AudioContext())
            {
                var test = 32;
                var oldUser = db.Users.FirstOrDefault(u => u.UserId == user.UserId);
                if (oldUser != null)
                    db.Users.Remove(oldUser);
                var dbUser = new Database.Models.User();
                dbUser.UserId = user.UserId;
                dbUser.FirstName = user.FirstName;
                dbUser.LastName = user.LastName;
                dbUser.Photo = user.Photo;
                db.Users.Add(dbUser);
                db.SaveChanges();
                var test2 = 33;
            }
        }
    }
}

Test/Test3/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Test3.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult LogIn()
        {
            return Redirect("https://oauth.vk.com/authorize?client_id=5703072&scope=8&redirect_uri=http://kobzar-001-site1.htempurl.com/Account/GetVkResponse");
        }

        [Route("getVkResponse")]
        public ActionResult GetVkResponse(string code)
        {
            if (code != null)
            {
                var req = WebRequest.Create("https://oauth.vk.com/access_token?client_id=5703072&client_secret=P5jEGgX6ocSbwVZI8qMz&redirect_uri=http://kobzar-001-site1.htempurl.com/Account/GetVkResponse&code=" + code);
                var resp = req.GetResponse();
                using (StreamReader stream = new StreamReader(resp.GetResponseStream()))
                {
                    var response = stream.ReadToEnd();
                    string cookie = Models.Auth.Authentication.Encrypt(response);
                    HttpCookie c = new HttpCookie(ConfigurationManager.AppSettings["CookieName"], cookie);
                    Response.Cookies.Add(c);
                }
                return RedirectToAction("Renew", "Account");
            }
            return HttpNotFound();
        }

        public ActionResult Renew()
        {
            Web.Models.AccountModel.RenewUserInfo();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult LogOut()
        {
            Response.Cookies.Remove(ConfigurationManager.AppSettings["CookieName"]);
            return RedirectToAction("Index", "Home");
        }

    }
}

Test/Test3/Controllers/AudioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Api.Requests;
using Api.Models;
using Database.Contexts;

namespace Test3.Controllers
{
    public partial class AudioController : Controller
    {
        // GET: Audio
        public ActionResult Get()
        {
            var audio = GetAudio.GetUserAudio(Models.Auth.Authentication.ResponseToken);
            return View("~/Views/Audio/_Audio.cshtml", audio);
        }

        public ActionResult Search(string titleQuery, string artistQuery, Ganres? ganre)
        {
            var audio = GetAudio.Search(titleQuery, artistQuery, ganre, Models.Auth.Authentication.ResponseToken);
            return View("~/Views/Audio/_Audio.cshtml", audio);
        }

        public JsonResult GetAudioData(int ownerId, int songId)
        {
            using (AudioContext db = new AudioContext())
            {
                var messages = db.Messages.Where(m => m.OwnerId == ownerId && m.SongId == songId).ToList();
                var result = messages.Select(m => new { message = m.Message, photo = m.User.Photo, time = m.Time }).OrderBy(m=>m.time).ToList();
                var ratings = db.Ratings.Where(r => r.OwnerId == ownerId && r.SongId == songId).ToList();
                var songRating = 0;
                if (ratings.Count > 0)
                {
                    var sum = ratings.Sum(r => r.Rate);
                    songRating = sum / ratings.Count;
                }
                var userRate = 0;
                if(ratings.FirstOrDefault(r=>r.UserId == Models.Auth.Authentication.UserId)!=null)
                {
                    userRate = ratings.FirstOrDefault(r => r.UserId == Models.Auth.Authentication.UserId).Rate;
                }
                var lyrics = Api.Requests.GetAudio.GetLirycs(songId, ownerId, Models.Auth.Authentication.ResponseToken);
                var text = lyrics.LyricsText.Replace("/n", "<br />");
                return Json(new { messages = result,songRate = songRating, userRate = userRate,lyrics= text }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Test/Test3/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Database.Contexts;
using Database.Models;

namespace Test3.Controllers
{
    public partial class AudioController : Controller
    {
        [HttpPost]
        public JsonResult AddMessage(int ownerId, int songId, int time, string message)
        {
            using (AudioContext db = new AudioContext())
            {
                ChatMessage m = new ChatMessage()
                {
                    Message = message,
                    OwnerId = ownerId,
                    SongId = songId,
                    Time = time,
                    UserId = Models.Auth.Authentication.UserId,
                    User_Id = Models.Auth.Authentication.CurrentUser.Id
                };
                db.Messages.Add(m);
                db.SaveChanges();
            }
            return Json("");
        }

        public JsonResult GetMessages(int ownerId, int songId)
        {
            using (AudioContext db = new AudioContext())
            {
                var messages = db.Messages.Where(m => m.OwnerId == ownerId && m.SongId == songId).ToList();
                var result = messages.Select(m => new { message = m.Message, photo = m.User.Photo, time = m.Time }).ToList();
                return Json(new { messages = result }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

Test/Test3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models.Auth;

namespace Test3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (Authentication.IsAuth)
            {
                return View();
            }
            else return RedirectToAction("Login", "Account");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Test/Test3/Controllers/RatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Database.Contexts;
using Database.Models;

namespace Test3.Controllers
{
    public partial class AudioController : Controller
    {
        // GET: Ratings
        public JsonResult AddRating(Rating rating)
        {
            using (AudioContext db = new AudioContext())
            {
                rating.UserId = Models.Auth.Authentication.UserId;
                db.Ratings.Add(rating);
                db.SaveChanges();
            }
            return Json("");
        }
    }
}

Test/Test3/Views/Audio/_Audio.cshtml
@model List<Api.Models.Audio>

@{
    Layout = null;
}

@if (Model.Count > 0)
{
    foreach (var a in Model)
    {
        <span>@a.Artist - @a.Title</span>
        <audio controls preload="none" data-duration="@a.Duration" data-owner-id="@a.OwnerId" data-song-id="@a.Id">
            <source src="@a.Url" />
        </audio>
    }
}
else
{
    <span>No Music Today :(</span>
}
<script>
    $(document).ready(function () {
        $("audio").on("play", function () {
            if (!$(this).hasClass("data-loaded")) {
                LoadData(this);
                $('.data-loaded').removeClass("data-loaded");
                $(this).addClass('data-loaded');
                lastSecond = 0;
                $("#MessagesPlace").html("");
            }
        });
        $("audio").on("timeupdate", function () {
            var currTime = Math.floor($(this).prop("currentTime"));
            if (currTime == lastSecond)
                return;
            lastSecond = currTime;
            for (var i = 0; i < currTime; i++) {
                $(".chat-message-row[data-time='" + i + "']").show();
            }
            var duration = Math.floor($(this).prop("duration"));
            for (var i = currTime; i < duration; i++) {
                $(".chat-message-row[data-time='" + i + "']").hide();
            }
        });
    })
</script>
@Scripts.Render("~/Scripts/Player/bootstrap3_player.js")

Test/Test3/Views/Home/About.cshtml

<button class="btn sorting" type="button" data-toggle="modal" data-target="#myModal">Фільтрувати<i class="glyphicon glyphicon-filter"></i></button>
<div id="myModal" class="modal fade" tabindex="-1"> 
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header"><button class="close" type="button" data-dismiss="modal">×</button>
<h4 class="modal-title">Фільтр</h4>
</div>
<div class="modal-body">    
    <span class="text-left">Назва треку  <input class="search-box" type="text" placeholder="Type something…"></span>
    <hr />
    <span class="text-left">Виконавець  <input class="search-box" type="text" placeholder="Type something…"></span>
    <hr />
    <span class="text-left">Жанр</span>
        <div class="dropdown search-box">           
            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Жанр музики<i class="glyphicon glyphicon-arrow-down"></i>
            </button>
<ul class="dropdown-menu">
 <li><a href="#">Реп(гавно)</a></li>
 <li><a href="#">Рок</a></li>
 <li><a href="#">Хіп-Хоп</a></li>
</ul>
</div>
    <hr />
    
        <span class="text-left">Оцінка</span>
    <div class="rating">
	         <span><img src="../../Content/img/star-off.png" class="img-responsive"/></span>
            <span><img src="../../Content/img/star-off.png" class="img-responsive"/></span>
            <span><img src="../../Content/img/star-off.png" class="img-responsive"/></span>
            <span><img src="../../Content/img/star-off.png" class="img-responsive"/></span>
            <span><img src="../../Content/img/star-off.png" class="img-responsive"/></span>
    </div>    
    </div>
<div class="modal-footer"><button class="btn btn-default" type="button" data-dismiss="modal">Закрыть</button></div>
</div>
</div>
</div>
<br />
<br />

<div class="tabs col-xs-5" style="float:right;">
  <!-- Навігація по вкладках -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#first-tab" aria-controls="first-tab" role="tab" data-toggle="tab">Лайвчат</a></li>
    <li><a href="#second-tab" aria-controls="second-tab" role="tab" data-toggle="tab">Текст пісні</a></li>
  </ul>
  <!-- Те що міститься в вкладках -->
  <div class="tab-content">

    <div role="tabpanel" class="tab-pane fade in active" id="first-tab">            <!--Перша вкладка-->
        <div class="live-chat col-xs-5" id="live-chat">
    
    <div class="row" style="overflow:hidden">
        <div id="MessagesPlace"></div>
    </div>

    <div class="row send-row">
        <div class="col-xs-10">
            @Html.TextBox("Message");
        </div>
        <div class="col-xs-2">
            <br /><input type="button" id="enterMessage" class="btn btn-primary form-horizontal send-massage" style="float: right; background-color:darkgoldenrod;" />
        </div>
    </div>    
    </div>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="second-tab">                     <!--Друга вкладка-->

        <div class="rating" style="float: left;">
	        <span><img src="../../Content/img/star-off.png" class="img-responsive"/></span>
            <span><img src="../../Content/img/star-off.png" class="img-responsive"/></span>
            <span><img src="../../Content/img/star-off.png" class="img-responsive"/></span>
            <span><img src="../../Content/img/star-off.png" class="img-responsive"/></span>
            <span><img src="../../Content/img/star-off.png" class="img-responsive"/></span>
    </div>  
    </div>       
    </div>
    </div>

<div id="raiting_star">
<div id="raiting">
<div id="raiting_blank"></div> <!--блок пустых звезд-->
<div id="raiting_hover"></div> <!--блок  звезд при наведении мышью-->
<div id="raiting_votes"></div> <!--блок с итогами голосов -->
</div>
<div id="raiting_info"><h5>Тут будет иконка загрузки и все такое</h5></div>
</div>





Test/Test3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Test/Test3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="row filters">
    @Html.Partial("~/Views/Home/_Partials/_Filters.cshtml")
</div>
<div class="row">
    <div class="col-xs-7 site-column audio-handler" id="audio-handler">
        @Html.Action("Get", "Audio");
    </div>
    <div class="col-xs-5 site-column chat-coments">
        <div class="tab-content">
            <div class="tab-pane fade in active" id="liveChatPane">
                @Html.Partial("~/Views/Home/_Partials/_LiveChat.cshtml")
            </div>
            <div class="tab-pane fade" id="ratingsPane">
                @Html.Partial("~/Views/Home/_Partials/_Ratings.cshtml")
            </div>
        </div>
    </div>
</div>

Test/Test3/Views/Home/_Partials/_Filters.cshtml
@{
    List<SelectListItem> ganres = new List<SelectListItem>();
    ganres.Add(new SelectListItem()
    {
        Text = "",
        Value = ""
    });
    foreach (Ganres ganre in Enum.GetValues(typeof(Ganres)))
    {
        ganres.Add(new SelectListItem() { Value = ((int)ganre).ToString(), Text = ganre.ToString() });
    }
}
<button class="btn sorting" type="button" data-toggle="modal" data-target="#myModal">Фільтрувати<i class="glyphicon glyphicon-filter"></i></button>
<ul class="nav nav-pills">
    <li class="active"><a data-toggle="pill" href="#liveChatPane">Чат</a></li>
    <li><a data-toggle="pill" href="#ratingsPane">Текст</a></li>
</ul>
<div id="myModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Фільтр</h4>
            </div>
            <div class="modal-body">
                <span class="text-left">Назва треку  <input class="search-box form-control" id="titleQuery" type="text" placeholder="Type something…"></span>
                <hr />
                <span class="text-left">Виконавець  <input class="search-box form-control" id="artistQuery" type="text" placeholder="Type something…"></span>
                <hr />
                <span class="text-left">Жанр</span>
                @Html.DropDownList("Ganre", ganres, new { @class = "selectpicker" })

                @*<span class="text-left">Оцінка</span>
                <div class="rating">
                    <span><img src="../../Content/img/star-off.png" /></span>
                    <span><img src="../../Content/img/star-off.png" /></span>
                    <span><img src="../../Content/img/star-off.png" /></span>
                    <span><img src="../../Content/img/star-off.png" /></span>
                    <span><img src="../../Content/img/star-off.png" /></span>
                </div>*@


            </div>
            <div class="modal-footer">
                <button class="btn btn-default" style="float:right" id="filter" type="button" data-dismiss="modal">Фільтрувати</button>
                <button class="btn btn-default" type="button" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<script>
    $("#filter").click(function () {
        var data = { titleQuery: $("#titleQuery").val(), artistQuery: $("#artistQuery").val(), ganre: $("#Ganre").val() }
       $.ajax({
            type: "POST",
            url: "../Audio/Search",
            data: JSON.stringify(data),
            dataType: "html",
            contentType: "application/json",
            success: function (response) {
                $("#audio-handler").html("");
                $("#audio-handler").html(response);
            }
        });
    });
</script>

Test/Test3/Views/Home/_Partials/_LiveChat.cshtml
@{
    Database.Models.User currentUser = Models.Auth.Authentication.CurrentUser;
}

<div class="live-chat" id="live-chat">
    <div class="row" style="overflow:hidden">
        <div id="MessagesPlace"></div>
    </div>

    <div class="row send-row">
        <div class="col-xs-10">
            <!--@Html.TextBox("Message","",new { @class="form-control"})-->
            <textarea id="Message" class="form-control" rows="3"></textarea>
        </div>
        <div class="col-xs-2" style="padding: 0px!important;">
            <button type="button" id="enterMessage" class="btn btn-primary">
                <i class="glyphicon glyphicon-envelope"></i>
            </button>
            
        </div>
    </div>
</div>

<script>
    var currUserPhoto = '@currentUser.Photo';
    var messages = [];
    var lastSecond = 0;

    $(document).ready(function () {
        var height = $('body').height();
        height -= $('.navbar.header').height();
        height -= $(".filters").height();
        height -= 30;
        $(".site-column").height(height);
        $("#MessagesPlace").height(height - $(".send-row").height());
        $("#Lyrics").height(height - $(".main-rating").height());

        $("#enterMessage").click(function () {
            var message = $("#Message").val();
            if (message == "" || message.replace(" ", "") == "")
                return;
            var currSong = $(".song-playing");
            if (currSong.length == 0)
                return;
            PushMessage(currUserPhoto, message, Math.floor($(currSong).prop("currentTime")), false);
            var data = { ownerId: currSong.attr("data-owner-id"), songId: currSong.attr("data-song-id"), time: currSong.prop("currentTime"), message: message };
            $("#Message").val("");
            $.ajax({
                type: "POST",
                url: "../Audio/AddMessage",
                data: JSON.stringify(data),
                dataType: "html",
                contentType: "application/json",
            });
        });
    });

    function PushMessage(photo,message,time,isHidden)
    {
        var display = isHidden ? "none" : "auto";
        var a = "<div class='row chat-message-row' style='display:"+display+";'data-time='"+time+"'></div>"
        var element = $(a);
        element.append("<div class='col-xs-2'></div>");
        element.append("<div class='col-xs-6'><span>" + message + "</span></div>");
        element.append("<div class='col-xs-2'><img src='"+photo+"' class='img-circle img-responsive' alt='Фото користувача'></div>");
        $("#MessagesPlace").append(element);
        $("#MessagesPlace").animate({ scrollTop: $('#MessagesPlace').prop("scrollHeight") }, 1000);
    }

    function LoadData(song)
    {
        var currSong = $(song);
        var data = { ownerId: currSong.attr("data-owner-id"), songId: currSong.attr("data-song-id") };
        $.ajax({
            type: "POST",
            url: "../Audio/GetAudioData",
            data: JSON.stringify(data),
            dataType: "html",
            contentType: "application/json",
            success:function(response)
            {
                var data = JSON.parse(response);
                messages = data.messages
                console.debug(data);
                $.each(messages, function () {
                    PushMessage(this.photo, this.message,this.time,true);
                });
                $(".main-rating > span").removeClass("user-rate").removeClass("song-rate");;
                if(data.userRate!=0)
                {
                    $(".main-rating > span[data-rate='" + data.userRate + "']").addClass("user-rate");
                }
                if(data.songRate!=0)
                {
                    $(".main-rating > span[data-rate='" + data.userRate + "']").addClass("song-rate");
                }
                $("#Lyrics>span").html(data.lyrics.replace(/(\r\n|\n|\r)/gm, "<br />"));
            }
        });
    }
</script>

<style>
    #MessagesPlace
    {
        overflow-y:auto;
    }

    #MessagesPlace::-webkit-scrollbar
    {
        display:none;
    }

    .chat-message-row span
    {
        word-wrap:break-word;
    }
</style>

Test/Test3/Views/Home/_Partials/_Ratings.cshtml
<div class="row rating main-rating">
    <span class="col-xs-2"></span>
    <span class="col-xs-2" data-rate="5"><img class="img-responsive" src="../../Content/img/star-off.png" /></span>
    <span class="col-xs-2" data-rate="4"><img class="img-responsive" src="../../Content/img/star-off.png" /></span>
    <span class="col-xs-2" data-rate="3"><img class="img-responsive" src="../../Content/img/star-off.png" /></span>
    <span class="col-xs-2" data-rate="2"><img class="img-responsive" src="../../Content/img/star-off.png" /></span>
    <span class="col-xs-2" data-rate="1"><img class="img-responsive" src="../../Content/img/star-off.png" /></span>
</div>

<div class="row">
    @*@Html.TextArea("Lyrics", new { @class = "form-control" });*@
    <div id="Lyrics" class="col-xs-12">
        <span></span>
    </div>
</div>
<style>
    .main-rating {
        margin: 0 0 10px 0px !important;
    }

        .main-rating span {
            float: right !important;
        }

    .song-rate:before,
    .song-rate ~ span:before {
        content: '';
        background: url('Content/img/star-on.png');
        background-repeat: no-repeat;
        background-size: contain;
        background-position: center;
        width: 120%;
        height: 120%;
        position: absolute !important;
    }

    #Lyrics{
        color:darkorange;
        overflow-y:auto;
    }
</style>

<script>
    $(document).ready(function () {
        $(".main-rating > span").on("click", function () {
            if ($(".main-rating .user-rate").length == 0) {
                var rate = $(this).attr("data-rate");
                if (rate != undefined) {
                    var currSong = $(".song-playing");
                    if (currSong.length == 0)
                        return;
                    $(this).addClass("user-rate");
                    if ($(".main-rating .song-rate").length == 0)
                        $(this).addClass("song-rate");
                    var data = { OwnerId: currSong.attr("data-owner-id"), SongId: currSong.attr("data-song-id"), Rate: rate };
                    $.ajax({
                        type: "POST",
                        url: "../Audio/AddRating",
                        data: JSON.stringify(data),
                        dataType: "html",
                        contentType: "application/json",
                    });
                }
            }
        });
    })
</script>

Test/Test3/Views/Shared/_Layout.cshtml
@{ 
    var currentUser = Models.Auth.Authentication.CurrentUser;
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Player/bootstrap3_player.css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/style.css?nocache="+DateTime.Now.ToShortDateString())
</head>
<body>
    <div class="page-wraper">
        <div class="navbar navbar-inverse header">
            <div class="container">
                <div class="navbar-header">
                    <!-- <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                         <span class="icon-bar"></span>
                         <span class="icon-bar"></span>
                         <span class="icon-bar"></span>
                     </button>-->
                    <ul class="nav navbar-nav navbar-left">
                        <li><a style="padding:0!important" class="navbar-brand" href="/"><img class="top_profil_image img-responsive img-circle" style="height:90px; margin:0!important;" src='Content/img/hedghack2.jpg' /></a></li>
                        <li class="divider"></li>   
                        <li><label class="user-name"style="margin-left:80px;margin-right:0px;">Hedgehog Music</label></li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><label class="user-name">@currentUser.FirstName @currentUser.LastName</label></li>
                        <li class="divider"></li>                        
                        <li><img src="@currentUser.Photo" class=" top_profil_image img-circle img-responsive" alt="Фото користувача"></li>
                        <li>
                            <a href="@Url.Action("Logout", "Account")" class="buttom-exit btn btn-small">
                                <i class="glyphicon glyphicon-off"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="body-content">
            @RenderBody()
            <!--<hr />-->
        </div>
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>